# Generated by Django 3.1.6 on 2021-02-18 21:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_auto_20210218_2057'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
